# VSCode setting.json:
#   "ruff.nativeServer": true,
#   "ruff.configuration": "/path/to/this/ruff.toml"

# default lint rules: ["E4", "E7", "E9", "F"]
# check https://docs.astral.sh/ruff/rules for more details
# selecing more rules with extend-select

line-length = 120

[lint]
extend-select = [
    "I",  # isort
    "PTH",  # flake8-use-pathlub
    "PD",  # pandas-vet
    "N"  # pep8-naming
]

[format]
quote-style = "single"